// <auto-generated />
using System;
using Credits.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Credits.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Credits.Domain.Entities.Credit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BilledAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("valor_faturado");

                    b.Property<decimal>("CalculationBase")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("base_calculo");

                    b.Property<DateOnly>("ConstitutionDate")
                        .HasColumnType("date")
                        .HasColumnName("data_constituicao");

                    b.Property<string>("CreditNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_credito");

                    b.Property<string>("CreditType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_credito");

                    b.Property<decimal>("DeductionAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("valor_deducao");

                    b.Property<bool>("IsSimpleNational")
                        .HasColumnType("boolean")
                        .HasColumnName("simples_nacional");

                    b.Property<decimal>("IssqnAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("valor_issqn");

                    b.Property<string>("NfseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_nfse");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("aliquota");

                    b.HasKey("Id");

                    b.HasIndex("CreditNumber")
                        .HasDatabaseName("ix_credito_numero_credito");

                    b.HasIndex("NfseNumber")
                        .HasDatabaseName("ix_credito_numero_nfse");

                    b.ToTable("credito", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
