services:

  api:
    build:
      context: .
      dockerfile: src/Credits.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceBus__ConnectionString=Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - ServiceBus__Subscription=credits-subscription
      - ServiceBus__AuditSubscription=audit-subscription
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=credits;Username=postgres;Password=postgres
    depends_on:
      - servicebus-emulator
      - postgres

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    ports:
      - "5672:5672"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd!Strong
      - SQL_SERVER=sqledge
    volumes:
      - ./config:/ServiceBus_Emulator/ConfigFiles:ro
    depends_on:
      - sqledge

  sqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd!Strong
    volumes:
      - sqledge_data:/var/opt/mssql

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: credits
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build:
      context: .
      dockerfile: src/Credits.Worker/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ServiceBus__ConnectionString=Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - ServiceBus__Subscription=credits-subscription
      - ServiceBus__Topics__IntegrateCreditConstituted=integrar-credito-constituido-entry
      - ServiceBus__Consumer__PollingIntervalMs=500
      - ServiceBus__Consumer__MaxWaitTimeMs=100
      - ServiceBus__Topics__NotificationAudit=notification-audit-entry
      - ServiceBus__AuditSubscription=audit-subscription
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=credits;Username=postgres;Password=postgres
    depends_on:
      - servicebus-emulator
      - postgres

volumes:
  postgres_data:
  sqledge_data: